// This file is autogenerated. Changes will be overwritten.
#include "FCRJAK7CAI/moc_EcatClient.cpp"
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "GYHJJKYD5Y/moc_BusStatsPlugin.cpp"
#include "I6CPM52TBP/moc_BusStatsService.cpp"
