// This file is autogenerated. Changes will be overwritten.
#include "I6CPM52TBP/moc_WorkflowAIService.cpp"
#include "I6CPM52TBP/moc_WorkflowCloudService.cpp"
#include "I6CPM52TBP/moc_WorkflowEdgeService.cpp"
#include "I6CPM52TBP/moc_WorkflowReplicationService.cpp"
