// This file is autogenerated. Changes will be overwritten.
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "YTEAPLTSM4/moc_ProjectPlugin.cpp"
#include "I6CPM52TBP/moc_ConfigurationService.cpp"
#include "I6CPM52TBP/moc_ProjectManagerService.cpp"
