// This file is autogenerated. Changes will be overwritten.
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "JYOBMPB44K/moc_EcatChartWidget.cpp"
#include "Y52NAPW6DN/moc_DashboardPlugin.cpp"
#include "I6CPM52TBP/moc_ChartService.cpp"
