// This file is autogenerated. Changes will be overwritten.
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "E54ZAO3K2U/moc_AdvancedErrorAnalysisPlugin.cpp"
#include "E54ZAO3K2U/moc_ErrorCorrelationWidget.cpp"
#include "E54ZAO3K2U/moc_ErrorTimelineWidget.cpp"
#include "I6CPM52TBP/moc_AdvancedErrorAnalysisService.cpp"
