// This file is autogenerated. Changes will be overwritten.
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "23DIFPFY7K/moc_PdoMappingCanvas.cpp"
#include "23DIFPFY7K/moc_PdoMappingEditorPlugin.cpp"
#include "I6CPM52TBP/moc_PdoMappingService.cpp"
