// This file is autogenerated. Changes will be overwritten.
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "LL6QG2GAJ5/moc_OscilloscopePlugin.cpp"
#include "LL6QG2GAJ5/moc_OscilloscopeService.cpp"
#include "LL6QG2GAJ5/moc_OscilloscopeWidget.cpp"
