// This file is autogenerated. Changes will be overwritten.
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "3QQTYVGSZ7/moc_WorkflowOptimizerPlugin.cpp"
#include "I6CPM52TBP/moc_WorkflowAnalyticsService.cpp"
