// This file is autogenerated. Changes will be overwritten.
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "AL2H7QR65A/moc_WorkflowDashboardPlugin.cpp"
#include "I6CPM52TBP/moc_WorkflowMonitoringService.cpp"
