// This file is autogenerated. Changes will be overwritten.
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "JH3W6KK32L/moc_LatencyOptimizerWidget.cpp"
#include "JH3W6KK32L/moc_RealtimeOptimizerPlugin.cpp"
#include "JH3W6KK32L/moc_ThroughputOptimizerWidget.cpp"
#include "I6CPM52TBP/moc_RealtimeOptimizerService.cpp"
