// This file is autogenerated. Changes will be overwritten.
#include "I6CPM52TBP/moc_WorkflowCertificationManagerService.cpp"
#include "I6CPM52TBP/moc_WorkflowComplianceManagerService.cpp"
#include "I6CPM52TBP/moc_WorkflowDocumentationBrowserService.cpp"
#include "I6CPM52TBP/moc_WorkflowSecurityManagerService.cpp"
