// This file is autogenerated. Changes will be overwritten.
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "RYBQCTISJ6/moc_WorkflowDesignerPlugin.cpp"
#include "I6CPM52TBP/moc_WorkflowOptimizationService.cpp"
#include "I6CPM52TBP/moc_WorkflowSchedulingService.cpp"
