// This file is autogenerated. Changes will be overwritten.
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "LMCRXGE3KQ/moc_OptimizationDashboardPlugin.cpp"
#include "I6CPM52TBP/moc_WorkflowMonitoringService.cpp"
#include "I6CPM52TBP/moc_WorkflowOptimizationService.cpp"
