// This file is autogenerated. Changes will be overwritten.
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "6LHVYWJ5ML/moc_MappingOptimizerWidget.cpp"
#include "6LHVYWJ5ML/moc_PdoMappingOptimizationPlugin.cpp"
#include "6LHVYWJ5ML/moc_SizeOptimizerWidget.cpp"
#include "I6CPM52TBP/moc_PdoMappingOptimizationService.cpp"
