// This file is autogenerated. Changes will be overwritten.
#include "ENDNMX37M4/moc_WorkspacePlugin.cpp"
#include "TBKREFF5SR/moc_AlarmPlugin.cpp"
#include "I6CPM52TBP/moc_AlarmService.cpp"
#include "I6CPM52TBP/moc_LoggingService.cpp"
